# Generated by Django 5.0.3 on 2024-04-02 22:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asteroid',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('normalized_matrix', models.TextField(unique=True)),
                ('cols', models.IntegerField()),
                ('rows', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('resolution', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Observatory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sighting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('matrix', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('asteroid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sightings', to='api.asteroid')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sightings', to='api.device')),
                ('observatory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sightings', to='api.observatory')),
            ],
            options={
                'unique_together': {('date', 'time', 'device', 'observatory', 'matrix')},
            },
        ),
    ]
